---
title: "Project"
author: "Srinath"
date: "2023-05-29"
output: word_document
---


```{r}
#library import
library(tidyverse)
library(ggplot2)
library(gridExtra)
library(pheatmap)
library(zoo)
```

```{r}
#Data Load
Data <- read.csv("C:\\Users\\srina\\Downloads\\patients.csv")
```

```{r}
#Read First Few rows
head(Data)
```
```{r}
##Data Dimension before deleting duplicates
dim(Data)
##Data Dimension after deleting duplicates
Unique_data<-unique(Data)
dim(Unique_data)
```
```{r}
##Target Distribution PIE chart
ggplot(Unique_data, aes(x = "", fill = factor(Diagnosis))) +
  geom_bar(width = 1) +
  coord_polar(theta = "y") +
  labs(fill = "Diagnosis") +
  ggtitle("Diagnosis Distribution") +
  theme_void()
```

```{r}
#Since data distribution of target variable is not even, followed downsizing of Diagnosis "0" underlined data 
# Subset the rows with Diagnosis value of 0
subset_data <- Data[Data$Diagnosis == 0, ]

# Check for 0 values in specified columns and remove the rows
filtered_data <- subset_data[!(subset_data$Glucose == 0 | subset_data$BloodPressure == 0 | subset_data$SkinThickness == 0 | subset_data$Insulin == 0 | subset_data$BMI == 0), ]

# Combine the filtered rows with the remaining rows that have Diagnosis value not equal to 0
final_data <- rbind(filtered_data, Data[Data$Diagnosis != 0, ])

# Reset row names
row.names(final_data) <- NULL

print(final_data)
```


```{r}
##PIe Chart
#distribution of traget variable post pre
ggplot(final_data, aes(x = "", fill = factor(Diagnosis))) +
  geom_bar(width = 1) +
  coord_polar(theta = "y") +
  labs(fill = "Diagnosis") +
  ggtitle("Diagnosis Distribution") +
  theme_void()
```


```{r}
#discriptive stats
summary(final_data[, 1:8])
```

```{r}
#EDA Visualization
##Box Plot
subset_data1 <- final_data[, 1:8]
long_data <- pivot_longer(subset_data1, everything(), names_to = "variable", values_to = "value")
ggplot(long_data, aes(x = variable, y = value)) +
  geom_boxplot() +
  xlab("") +
  ylab("Value") +
  theme_minimal()
```

```{r}
##Histogram
Pregnancies <- ggplot(final_data, aes(x = Pregnancies)) + geom_histogram() + ggtitle("Pregnancies")
Glucose <- ggplot(final_data, aes(x = Glucose)) + geom_histogram() + ggtitle("Glucose")
BloodPressure <- ggplot(final_data, aes(x = BloodPressure)) + geom_histogram() + ggtitle("Blood Pressure")
SkinThickness <- ggplot(final_data, aes(x = SkinThickness)) + geom_histogram() + ggtitle("Skin Thickness")
Insulin <- ggplot(final_data, aes(x = Insulin)) + geom_histogram() + ggtitle("Insulin")
BMI <- ggplot(final_data, aes(x = BMI)) + geom_histogram() + ggtitle("BMI")
Pedigree <- ggplot(final_data, aes(x = Pedigree)) + geom_histogram() + ggtitle("Pedigree")
Age <- ggplot(final_data, aes(x = Age)) + geom_histogram() + ggtitle("Age")
grid.arrange(
  Pregnancies, Glucose, BloodPressure, SkinThickness,
  Insulin, BMI, Pedigree, Age,
  nrow = 3
)

```



```{r}
##Data Cleaning
##all zeros were said to be as NA's hence i would replace the zeros with Medians
for (i in 1:8) {
  final_data[, i] <- ifelse(final_data[, i] == 0, median(final_data[final_data[, i] != 0, i], na.rm = TRUE), final_data[, i])
}

```

```{r}
##Read First Few rows to see if 0's were replaced by median of the column
head(final_data)
```

```{r}
##Removing outliers using capping method
treating_outliers <- function(x) {
  qntls <- quantile(x, probs = c(0.25, 0.75))
  iqr <- qntls[2] - qntls[1]
  lb <- qntls[1] - 1.5 * iqr
  ub <- qntls[2] + 1.5 * iqr
  x[x < lb] <- lb
  x[x > ub] <- ub
  return(x)
}

final_data[, 1:8] <- apply(final_data[, 1:8], 2, treating_outliers)


##Box Plot
subset_data <- final_data[, 1:8]
long_data <- pivot_longer(subset_data, everything(), names_to = "variable", values_to = "value")
ggplot(long_data, aes(x = variable, y = value)) +
  geom_boxplot() +
  xlab("") +
  ylab("Value") +
  theme_minimal()

```
```{r}
#test check the normality
variables <- c("Pregnancies", "Glucose", "BloodPressure", "SkinThickness", "Insulin", "BMI", "Pedigree", "Age")

# Loop through variables
for (variable in variables) {
  # Perform Shapiro-Wilk test for normality
  shapiro_test <- shapiro.test(final_data[[variable]])
  
  # Print variable name and test results
  cat("Variable:", variable, "\n")
  cat("Shapiro-Wilk test statistic (W):", shapiro_test$statistic, "\n")
  cat("Shapiro-Wilk test p-value:", shapiro_test$p.value, "\n")
  cat("\n")
}

```

```{r}
##check summary post data cleaning
summary(final_data[, 1:8])
```


```{r}
##Correlation Matrix
#check Coorelation post data cleaning
Correlation_Mtrx <- cor(final_data)
Correlation_Percentages <- round(Correlation_Mtrx * 100, 2)
pheatmap(Correlation_Percentages,
         main = "Correlation Matrix (%)",
         fontsize = 10,
         fontsize_row = 8,
         fontsize_col = 8,
         color = colorRampPalette(c("navy", "white", "firebrick3"))(100),
         show_rownames = TRUE,
         show_colnames = TRUE,
         display_numbers = TRUE,
         number_color = "black",
         number_format = "%.2f%%")

```

